// 商品リストの配列
const database = [
  {
      "project_id": 0,
      "title": "【AI・クローラーエンジニア】HR Tech業界で人材と企業を独自のアルゴリズムで結び付け、新たな理論を創ったプラットフォームサービス 一緒に将来を担っていけるメンバーを募集します！",
      "company": "株式会社エイト",
      "job": "エンジニア",
      "position": "バックエンドエンジニア",
      "prefecture": "東京都",
      "city": "渋谷",
      "monthly_income_min": "70万",
      "monthly_income_max": "90万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "PHP，Ruby，Java，Python，AWS，Apache，Firebase，Cordova",
      "want_skill": "開発経験3年以上",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "35",
      "working_type": "正社員",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年4月29日",
      "sales_name": "吉田 太郎"
  },
  {
      "project_id": 1,
      "title": "【最先端のAI・アドテク活用】急成長中の企業で、会社の“顔”となる自社プロダクトの開発したい方 大募集！【最先端のAI・アドテク活用】急成長中の企業で、会社の“顔”となる自社プロダクトの開発したい方 大募集！【最先端のAI・アドテク活用】急成長中の企業で、会社の“顔”となる自社プロダクトの開発したい方 大募集！【最先端のAI・アドテク活用】急成長中の企業で、会社の“顔”となる自社プロダクトの開発したい方 大募集！【最先端のAI・アドテク活用】急成長中の企業で、会社の“顔”となる自社プロダクトの開発したい方 大募集！",
      "company": "Tech 株式会社",
      "job": "エンジニア",
      "position": "データベースエンジニア",
      "prefecture": "東京都",
      "city": "池袋",
      "monthly_income_min": "40万",
      "monthly_income_max": "50万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "MySQL，nginx，PostgreSQL，Apache，Jenkins，Elasticsearch，Redis，SRE,MySQL，nginx，PostgreSQL，Apache，Jenkins，Elasticsearch，Redis，SRE, MySQL，nginx，PostgreSQL，Apache，Jenkins，Elasticsearch，Redis，SRE,MySQL，nginx，PostgreSQL，Apache，Jenkins，Elasticsearch，Redis，SRE",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js, React, AWS, SCSS, JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js, React, AWS, SCSS, JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js, React, AWS, SCSS, ",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。案件自体はこちらで要件を決めて落としますが、どうするべきかという指導もできる人材だとなお好ましい案件自体はこちらで要件を決めて落としますが、どうするべきかという指導もできる人材だとなお好ましい案件自体はこちらで要件を決めて落としますが、どうするべきかという指導もできる人材だとなお好ましい案件自体はこちらで要件を決めて落としますが、どうするべきかという指導もできる人材だとなお好ましい案件自体はこちらで要件を決めて落としますが、どうするべきかという指導もできる人材だとなお好ましい案件自体はこちらで要件を決めて落としますが、どうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましいどうするべきかという指導もできる人材だとなお好ましい",
      "time": "2ヶ月 ~",
      "matching": "39",
      "working_type": "業務委託",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年4月20日",
      "sales_name": "佐藤 しおり"
  },
  {
      "project_id": 3,
      "title": "急成長FinTechスタートアップのpythonエンジニアを大募集！",
      "company": "FinTech 株式会社",
      "job": "エンジニア",
      "position": "ネットワークエンジニア",
      "prefecture": "東京都",
      "city": "多摩",
      "monthly_income_min": "80万",
      "monthly_income_max": "110万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "アルバイト",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  },
  {
      "project_id": 4,
      "title": "【Web開発】キャリアの選択肢も無限大！/上流工程から参画/複数のWeb開発プロジェクトで経験を積んでスキルアップ可能です！",
      "company": "FinTech 株式会社",
      "job": "エンジニア",
      "position": "ネットワークエンジニア",
      "prefecture": "千葉県",
      "city": "四街道",
      "monthly_income_min": "40万",
      "monthly_income_max": "50万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "PHP，Ruby，Java，Python，Go，Node.js，React，vue.js，angular",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "アルバイト",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  },
  {
      "project_id": 5,
      "title": "【webエンジニア】フルスタックエンジニアとして活躍してください！",
      "company": "FinTech 株式会社",
      "job": "エンジニア",
      "position": "サーバーエンジニア",
      "prefecture": "東京都",
      "city": "多摩",
      "monthly_income_min": "80万",
      "monthly_income_max": "110万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "アルバイト",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  },
  {
      "project_id": 6,
      "title": "【SE / PG】自社開発クラウド案件／モダン開発・GCPなどに興味があるエンジニア大歓迎！3年連続Google Awardを受賞したアジアNo1企業",
      "company": "FinTech 株式会社",
      "job": "エンジニア",
      "position": "サーバーエンジニア",
      "prefecture": "東京都",
      "city": "多摩",
      "monthly_income_min": "80万",
      "monthly_income_max": "110万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "アルバイト",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  },
  {
      "project_id": 7,
      "title": "【Rails】主力事業BOXILをネクストステージに押し上げるグロースエンジニア募集！エンジニアのパフォーマンスの出しやすさに注力した環境で能力発揮しませんか？",
      "company": "ロプ 株式会社",
      "job": "エンジニア",
      "position": "サーバーエンジニア",
      "prefecture": "東京都",
      "city": "多摩",
      "monthly_income_min": "80万",
      "monthly_income_max": "110万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "C，JavaScript，PHP，Java，Python，Go，Node.js，TypeScript，Android，TensorFlow，Kotlin",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "正社員",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  },
  {
      "project_id": 8,
      "title": "急成長FinTechスタートアップのpythonエンジニアを大募集！",
      "company": "FinTech 株式会社",
      "job": "エンジニア",
      "position": "プロジェクトマネージャー",
      "prefecture": "東京都",
      "city": "多摩",
      "monthly_income_min": "80万",
      "monthly_income_max": "110万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "業務委託",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  },
  {
      "project_id": 9,
      "title": "【Python使い倒す】Python×Djangoを使った自社開発！「開発好きな気持ち」重視します。",
      "company": "FinTech 株式会社",
      "job": "エンジニア",
      "position": "CTO候補",
      "prefecture": "東京都",
      "city": "多摩",
      "monthly_income_min": "80万",
      "monthly_income_max": "110万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "アルバイト",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  },
  {
      "project_id": 10,
      "title": "【SE / PG】自社開発クラウド案件／モダン開発・GCPなどに興味があるエンジニア大歓迎！3年連続Google Awardを受賞したアジアNo1企業",
      "company": "FinTech 株式会社",
      "job": "エンジニア",
      "position": "プロジェクトマネージャー(PM)",
      "prefecture": "東京都",
      "city": "多摩",
      "monthly_income_min": "80万",
      "monthly_income_max": "110万",
      "monthly_income": "80万",
      "working_days": "週3",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "業務委託",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  },
  {
      "project_id": 11,
      "title": "【開発SE・プログラマ（東京勤務）】年間休日128日 / 残業月平均13時間 【WEB面接可能】◎エンジニアの働きやすさを極限まで追求しました！",
      "company": "EnginTech 株式会社",
      "job": "エンジニア",
      "position": "バックエンドエンジニア",
      "prefecture": "東京都",
      "city": "多摩",
      "monthly_income_min": "20万",
      "monthly_income_max": "30万",
      "monthly_income": "80万",
      "working_days": "週1",
      "salary": "80万",
      "vacation": "夏期冬季休暇あり。GW、お盆休みあり。",
      "must_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "want_skill": "JavaScript, PHP, Java, Python, MySQL, Vue.js, Node,js",
      "mendann": "1回",
      "welfare": "年間休日120!!! 社保完備、会社内旅行あり",
      "agent_comment": "Pythonによる入札額及び日予算の最適化ロジックの開発に携わっていただきます。Python実務経験が1年以上ある方にマッチします。※担当者は変更になる場合がございます",
      "project_detail": "容電子決済サービス向けプロダクトの機能追加がメインの作業となりますが、サービス全体を俯瞰してシステム構築作業にも携わっていただきます。",
      "time": "2ヶ月 ~",
      "matching": "20",
      "working_type": "正社員",
      "want_person": "わからないことがあっても積極的に質問ができ、自ら行動ができる方。",
      "email": "sato@example.com",
      "created_at": "2020年5月1日",
      "sales_name": "川崎 勇気"
  }
]
var databaseResult = [];
const data = axios.get('http://localhost:3000/mock/users').then(response => databaseResult = response.data)
console.log(data)
const result = data.then((value) => { return value });
console.log(result)
// data.then((value) => {
//   console.log(value);
//   return value
// });



// インポート先で使用できる関数をオブジェクトとしてまとめたもの
import axios from 'axios'
export default {
  data() {
    return {
      database1: []
    }
  },
  fetch(id, value) {
    // * dataから取り出す ...できない
    // var sample = axios.get('http://localhost:3000/mock/users')
    // .then
    //   (response => this.projects = response.data)
    // console.log(sample)
    // return sample
    // data.then((value) => {
    //   console.log(value);
    //   return value
    // });
    console.log("~~~~~~~~~~変わらない~~~~~~~~~")
    // return value
    return database
  },
  find(project_id) { // 追記した関数
    return database.find(el => el.project_id === project_id)
  },
  asyncFind(project_id) {
    return new Promise(res => setTimeout(() => {
      res(this.find(project_id))
    }, 1000))
  }
}